# ----
# Site

title: Houzi Docs
url: "https://houzi-doc.booleanbites.com"
baseurl: 
google_analytics_key: G-BE9JVJ5QL4
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for Houzi real estate app.
author:
  name: Adil Soomro
  email: houziapp@gmail.com
  twitter: booleanbites
social:
  name: Houzi
  links:
    - https://houzi.booleanbites.com
    - https://play.google.com/store/apps/details?id=com.booleanbites.houzez
    - https://apps.apple.com/us/app/id1598357211

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
